### ISSUE TITLE
System further expanded

### ISSUE THREAD

**Issue by WuZihao12** [IRVLab/spline_vio#1]
Hello and thanks for your work. What I want to ask is how to add other sensors based on your work, such as adding an asynchronous camera? do you have any good advice?

**Comment by jiawei-mo** [comment]
Hi,

Thank you for your interest in our work. For any additional sensor, I would query the pose at the timestamp from the spline, transform the pose to that sensor frame, calculate the error, and update the state. Hope that helps.

Best,
Jiawei
